CREATE TABLE applicants (

    applicant_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    supabase_user_id UUID UNIQUE,
    first_name VARCHAR(100) NOT NULL,
    middle_name VARCHAR(100),
    last_name VARCHAR(100) NOT NULL,
    dob DATE NOT NULL,
    gender_id BIGINT REFERENCES gender(gender_id),
    marital_status_id BIGINT REFERENCES marital_status(marital_status_id),
    education_level_id BIGINT REFERENCES education_level(education_level_id),
    pan_number VARCHAR(10) UNIQUE,
    aadhaar_number VARCHAR(12) UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(15) NOT NULL,
    address_line1 TEXT NOT NULL,
    address_line2 TEXT,
    city VARCHAR(100) NOT NULL,
    state_id BIGINT REFERENCES states(state_id),
    pincode VARCHAR(6) NOT NULL,
    occupation_id BIGINT REFERENCES occupation(occupation_id),
    employer_name VARCHAR(255),
    employment_type_id BIGINT REFERENCES employment_types(employment_type_id),
    monthly_income NUMERIC(15, 2) NOT NULL,
    income_type_id BIGINT REFERENCES income_types(income_type_id),
    account_type_id BIGINT REFERENCES account_types(account_type_id),
    bank_name VARCHAR(255),
    account_number VARCHAR(20),
    ifsc_code VARCHAR(11),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()

);
